NAME = ../PecoRename
TYPE = SHARED
SRCS = main.cpp
RDEFS = pecorename_addon.rdef
RSRCS = 
LIBS = be
LIBPATHS=
SYSTEM_INCLUDE_PATHS=
LOCAL_INCLUDE_PATHS=
OPTIMIZE=FULL
DEFINES=
WARNINGS =
SYMBOLS=
COMPILER_FLAGS=-Woverloaded-virtual -funsigned-bitfields -Wwrite-strings
LINKER_FLAGS=

## include the makefile-engine
DEVEL_DIRECTORY := \
	$(shell findpaths -r "makefile_engine" B_FIND_PATH_DEVELOP_DIRECTORY)
include $(DEVEL_DIRECTORY)/etc/makefile-engine
