NAME= ../PecoRename
TYPE= APP
SRCS= main.cpp constants.cpp functions.cpp BottomView.cpp Fenster.cpp FileListItem.cpp FileListView.cpp FileView.cpp LiveTextControl.cpp MainView.cpp Panel.cpp PecoApp.cpp ScriptFilePanel.cpp TopView.cpp Renamer.cpp Renamer_SearchReplace.cpp Renamer_InsertReplace.cpp Renamer_Remove.cpp Renamer_Numbering.cpp Renamer_Extension.cpp Renamer_UpperLower.cpp About.cpp
RSRCS= About.rsrc FileInfo.rsrc
LIBS= /boot/develop/lib/x86/libbe.so /boot/develop/lib/x86/libstdc++.r4.so /boot/develop/lib/x86/libtextencoding.so /boot/develop/lib/x86/libtracker.so
LIBPATHS=
SYSTEM_INCLUDE_PATHS= /boot/develop/headers/be /boot/develop/headers/cpp /boot/develop/headers/posix /boot/develop/lib /boot/beos/system/lib
LOCAL_INCLUDE_PATHS=
OPTIMIZE=FULL
#	specify any preprocessor symbols to be defined.  The symbols will not
#	have their values set automatically; you must supply the value (if any)
#	to use.  For example, setting DEFINES to "DEBUG=1" will cause the
#	compiler option "-DDEBUG=1" to be used.  Setting DEFINES to "DEBUG"
#	would pass "-DDEBUG" on the compiler's command line.
DEFINES=
#	specify special warning levels
#	if unspecified default warnings will be used
#	NONE = supress all warnings
#	ALL = enable all warnings
WARNINGS =
# Build with debugging symbols if set to TRUE
SYMBOLS=
COMPILER_FLAGS=-Woverloaded-virtual -funsigned-bitfields -Wwrite-strings 
LINKER_FLAGS=

## include the makefile-engine
include $(BUILDHOME)/etc/makefile-engine
