NAME = PecoRename-R
TYPE = SHARED
SRCS = main.cpp
RSRCS = FileInfo.rsrc
LIBS = be
LIBPATHS=
SYSTEM_INCLUDE_PATHS=
LOCAL_INCLUDE_PATHS=
OPTIMIZE=FULL
DEFINES=
WARNINGS =
SYMBOLS=
COMPILER_FLAGS=-Woverloaded-virtual -funsigned-bitfields -Wwrite-strings
LINKER_FLAGS=

## include the makefile-engine
include $(BUILDHOME)/etc/makefile-engine
